version: '3.7'
services:
  web:
    build: .
    container_name: django
    command: sh -c "python /usr/src/app/manage.py migrate --noinput &&
                    python manage.py collectstatic --no-input &&
                    gunicorn kayak_tour.wsgi:application -b 0.0.0.0:8000 --reload"
    volumes:
      - static_volume:/usr/src/app/staticfiles
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=aboba123
      - POSTGRES_DB=bot_db
    ports:
      - "5432:5432"
  bot:
    build: .
    container_name: tg_bot
    command: python run_pooling.py
    env_file:
      - ./.env.prod
    depends_on:
      - web
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - web
      - db
    ports:
      - "80:80"
    volumes:
      - static_volume:/usr/src/app/staticfiles


volumes:
  postgres_data:
  static_volume: