# Generated by Django 3.2.6 on 2021-08-19 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RentObject',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rent_type', models.CharField(choices=[('ka', 'Каяк'), ('su', 'SUP'), ('wi', 'Wind SUP')], max_length=2, verbose_name='Вид')),
                ('advanced_rent_type', models.CharField(choices=[('Каяк', (('op', 'Открытый'), ('cl', 'Закрытый')))], max_length=2, verbose_name='Тип')),
                ('name', models.CharField(max_length=128, verbose_name='Имя')),
                ('amount', models.IntegerField(default=1, verbose_name='Количество')),
                ('capacity', models.IntegerField(default=1, verbose_name='Взрослый')),
                ('child_capacity', models.IntegerField(default=0, verbose_name='Ребенок')),
                ('hour_price', models.IntegerField(default=600, verbose_name='Час')),
                ('four_hour_price', models.IntegerField(default=1300, verbose_name='4 часа')),
                ('daytime_price', models.IntegerField(default=1600, verbose_name='День')),
                ('all_day_price', models.IntegerField(default=2000, verbose_name='Сутки')),
                ('description', models.TextField(max_length=4096, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать')),
            ],
        ),
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='Имя')),
                ('description', models.CharField(max_length=256, verbose_name='Описание')),
                ('content', models.TextField(max_length=4096, verbose_name='Текст')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id')),
                ('username', models.CharField(blank=True, max_length=32, null=True, verbose_name='Ник')),
                ('first_name', models.CharField(max_length=256, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('language_code', models.CharField(blank=True, help_text="Telegram client's lang", max_length=8, null=True, verbose_name='Язык')),
                ('is_blocked_bot', models.BooleanField(default=False, verbose_name='Заблокировал бота')),
                ('is_banned', models.BooleanField(default=False, verbose_name='В бане')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Админ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128, verbose_name='Действие')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.user', verbose_name='Пользователь')),
            ],
        ),
    ]
