# Generated by Django 3.2.6 on 2021-08-17 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticText',
            fields=[
                ('name', models.CharField(max_length=256, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=256)),
                ('content', models.CharField(max_length=4096)),
            ],
        ),
    ]
